@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "fr.upem.net.tcp.chatfusion.client.ClientChatFusion#getPath()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "fr.upem.net.tcp.chatfusion.client.ClientChatFusion",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_3596419 { 
   	label=upem
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1360230834 { 
   	label=net
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1171374913 { 
   	label=ClientChatFusion
	labeljust=l
	fillcolor=white
	style=filled
   
   ClientChatFusion1030237686XXXgetPath0[
	label="+ getPath()"
	style=filled
	fillcolor=white
	tooltip="ClientChatFusion

&#10;  Gets the folder's path where the file will be&#10;  sent or received&#10;  @return&#10; "
	penwidth=4
	fontcolor=darkgreen
];

ClientChatFusion1030237686XXXlaunch0[
	label="+ launch()"
	style=filled
	fillcolor=white
	tooltip="ClientChatFusion

&#10;  Launches the client&#10;  @throws IOException if an I/O error occurs&#10; "
	fontcolor=darkgreen
];

ClientChatFusion1030237686XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="ClientChatFusion

&#10;  @throws NumberFormatException if a conversion is attempted from a bad format&#10; string to a numeric type&#10;  @throws IOExceptionif an I/O error occurs&#10; "
	fontcolor=darkgreen
];
} 

subgraph cluster_809212336 { 
   	label=Commander
	labeljust=l
	fillcolor=white
	style=filled
   
   Commander50095398XXXtreatPrivateFile2118012780[
	label="+ treatPrivateFile()"
	style=filled
	fillcolor=white
	tooltip="Commander

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
ClientChatFusion1030237686XXXlaunch0 -> Commander50095398XXXtreatPrivateFile2118012780;
ClientChatFusion1030237686XXXmain1859653459 -> ClientChatFusion1030237686XXXlaunch0;
Commander50095398XXXtreatPrivateFile2118012780 -> ClientChatFusion1030237686XXXgetPath0;
    
}
@enduml